### ISSUE TITLE
Timestamp parsing error when printing a CVE entry

### ISSUE THREAD

**Issue by msmeissn** [RedHatProductSecurity/cvelib#1]
i am trying to

cve -o suse -u meissner@suse.de -a KEY list

and I get:

ValueError: time data '2019-01-03T00:00:00.000Z' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

any idea ... the string looks as it should match :(

**Comment by mprpic** [comment]
@msmeissn Ah, seems that Python 3.6 does not handle `%z`; it was only included in 3.7:

https://stackoverflow.com/questions/53291250/python-3-6-datetime-strptime-returns-error-while-python-3-7-works-well

From Python 3.7 changelog:

> bpo-31800: Extended support for parsing UTC offsets. strptime ‘%z’ can now parse the output generated by datetime.isoformat, including seconds and microseconds.

I'll submit a fix for this, thanks for the report! In the mean time, you can use `--raw` to print the JSON response and parse it with `jq` if you'd like.

**Comment by msmeissn** [comment]
can confirm it works now after above fix

**Comment by mprpic** [comment]
This is now fixed and released in version 0.3.0.
