### ISSUE TITLE
Protection of API key

### ISSUE THREAD

**Issue by raschi-de** [RedHatProductSecurity/cvelib#13]
The API key essentially works like a password and I think it should be protected as such. Especially for interactive command line, it is not a good practice to store the API key as accessible as environment variables or type it in the command (and thus expose it in command history).

I suggest that at least in interactive mode it should be possible to ommit the -a option and the tool should then ask the user interactively to enter the password (ideally with obscured or no UI feedback). That is how for example openssh CLI handles the protection of the SSH key / user password.

**Comment by mprpic** [comment]
Specifying API tokens through environment variables is pretty standard as was as CLI tools go, see e.g.:
- https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
- https://developers.cloudflare.com/cloudflare-one/tutorials/cli#using-the-token-as-an-environment-variable
- https://cli.github.com/manual/gh_help_environment

We could certainly modify the behavior to prompt for the token if neither the env var is configured nor the `-a` option used, that should be an easy fix. Note though that you'll have to submit the token on every command since each request requires it and there is no caching or session support built into the library right now.

For a better solution, we could define a config file where you could specify the credentials or alternatively a command that fetches them, akin to AWS's cli: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

That's a larger feature though and should probably be filed separately if desired.

**Comment by mprpic** [comment]
Implemented in https://github.com/RedHatProductSecurity/cvelib/commit/f5db6fa8d19c062b7c95830e7e75a806ee76328c

If neither the option or the env var is specified, you'll get a prompt with a hidden input, e.g.:

```
$ cve -u joe -o acme quota
API key: 
...
```

**Comment by raschi-de** [comment]
Thanks for picking up the suggestion - I agree that it is only relevant / useable for interactive command line use cases, as stated in the original request (and other tools like OpenSSH do exactly that).

**Comment by raschi-de** [comment]
Hi Martin,

 

sorry for being stupid and for bothering you still - I seem to be running
into an issue here. I must admit, I am not that familiar with Python on
Windows, but when working for ABB, I have to use what I have.

 

C:\Users\DEU216201>cve --version

cvelib 0.5.0

 

C:\Users\DEU216201>cve -u ***@***.*** -o ABB quota

Usage: cve [OPTIONS] COMMAND [ARGS]...

Try 'cve -h' for help.

 

Error: Missing option '-a' / '--api-key'.

 

I even tried a fresh install on a personal laptop according to the
instructions.

 

Any suggestion?

 

Cheers,

 

                Ragnar 

 

 



 

 

-

Ragnar Schierholz

Head of Cyber Security, Process Automation

 

ABB Automation GmbH

Schillerstr. 72

DE-32425 Minden, Germany

Phone: +49-571-830-1080

Mobile: +49-171-189-2349

Visit us at  <http://www.abb.com/cybersecurity> www.abb.com/cybersecurity

 

ABB Automation GmbH
Sitz/Head Office: Mannheim 
Registergericht/Registry Court: Mannheim 
Handelsregisternummer/Commercial Register No.: HRB 10111 
Geschäftsführung/Managing Board: Ekkehard Neureither
(Vorsitzender/Chairman), Jörg Reger 
Vorsitzender des Aufsichtsrats/Chairman of Supervisory Board: Markus Ochsner

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail ist nicht gestattet. 

Bitte beachten Sie auch unsere Datenschutzerklärung für Geschäftspartner,
die Sie über unsere  <https://new.abb.com/privacy-policy/de/datenschutz>
Webseite oder direkt unter diesem
<https://new.abb.com/docs/librariesprovider30/default-document-library/daten
schutzerklärung-geschäftspartner-abb-ag_de832794ecc1f463c09537ff0000433538.p
df> Link finden.

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorized copying, disclosure or distribution of the material in this
e-mail is strictly forbidden.

Please also take note of our data protection notice for business partners,
which you can find on our
<https://new.abb.com/privacy-policy/de/datenschutz> web page or directly
under the following
<https://new.abb.com/docs/librariesprovider30/default-document-library/data-
protection-notice-business-partners-abb-ag_de762794ecc1f463c09537ff000043353
8.pdf> link.

 

From: Martin Prpič ***@***.***> 
Sent: Mittwoch, 15. Dezember 2021 01:46
To: RedHatProductSecurity/cvelib ***@***.***>
Cc: Ragnar Schierholz ***@***.***>; Author
***@***.***>
Subject: Re: [RedHatProductSecurity/cvelib] Protection of API key (Issue
#13)

 

	
This email originated from outside of your organization. Please do not click
on links or open attachments unless you recognize the sender and know the
content is safe. 

 

Implemented in
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FRedHatProductSecurity%2Fcvelib%2Fcommit%2Ff5db6fa8d19c062b7c95830e7e75a8
06ee76328c&data=04%7C01%7Cragnar.schierholz%40de.abb.com%7Cfd1c4059a7a74c05b
da508d9bf6443d9%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637751259623670
246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1h
aWwiLCJXVCI6Mn0%3D%7C3000&sdata=jdvquxMYshkTaGBQI717xK8tnprT9lszT99vFC03NDI%
3D&reserved=0> f5db6fa

If neither the option or the env var is specified, you'll get a prompt with
a hidden input, e.g.:

$ cve -u joe -o acme quota
API key: 
...

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FRedHatProductSecurity%2Fcvelib%2Fissues%2F13%23issuecomment-994182634&da
ta=04%7C01%7Cragnar.schierholz%40de.abb.com%7Cfd1c4059a7a74c05bda508d9bf6443
d9%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637751259623670246%7CUnknown
%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6M
n0%3D%7C3000&sdata=FBUM%2B3DzONRf4UXP%2Bd3QB4BPpZXGgPnPfNur5%2F4y22s%3D&rese
rved=0> , or unsubscribe
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAQYN5KWKUQFLPTT3GOQDVJLUQ7QMPANCNFSM5
JZPVHGA&data=04%7C01%7Cragnar.schierholz%40de.abb.com%7Cfd1c4059a7a74c05bda5
08d9bf6443d9%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637751259623670246
%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWw
iLCJXVCI6Mn0%3D%7C3000&sdata=Qe%2BFEe%2FCiNDeQgSayTWPlij4hKbRE%2BlCeWXStwja0
2g%3D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.appl
e.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%
26pt%3D524675&data=04%7C01%7Cragnar.schierholz%40de.abb.com%7Cfd1c4059a7a74c
05bda508d9bf6443d9%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637751259623
670246%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6I
k1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uvNlCjlhsjO%2FRNqZhxAyZcDkd%2BVDFUdxkeqqS
6GV4RQ%3D&reserved=0>  or Android.

**Comment by mprpic** [comment]
Hey @raschi-de, not a stupid question at all :-) I pushed the fix to this repo but have not published an updated package of cvelib to PyPI yet so the version available there (0.5.0 at the moment) does not contain this code change. I'll push out a new update some time today and then you can just run `python3 -m pip install --upgrade`. Look out for a new release to be available in either of these places:
- https://pypi.org/project/cvelib/#history
- https://github.com/RedHatProductSecurity/cvelib/releases

**Comment by raschi-de** [comment]
Hi,

 

Thanks for bearing with me. I noticed that the version in GitHub was still
unchanged, but figured such change may be too small to justify a new
version.

 

Of course this is not terribly urgent, I'll keep my eyes open (and myself
busy with Log4Shell response.).

 

Cheers,

 

                Ragnar

 

 

 



 

 

-

Ragnar Schierholz

Head of Cyber Security, Process Automation

 

ABB Automation GmbH

Schillerstr. 72

DE-32425 Minden, Germany

Phone: +49-571-830-1080

Mobile: +49-171-189-2349

Visit us at  <http://www.abb.com/cybersecurity> www.abb.com/cybersecurity

 

ABB Automation GmbH
Sitz/Head Office: Mannheim 
Registergericht/Registry Court: Mannheim 
Handelsregisternummer/Commercial Register No.: HRB 10111 
Geschäftsführung/Managing Board: Ekkehard Neureither
(Vorsitzender/Chairman), Jörg Reger 
Vorsitzender des Aufsichtsrats/Chairman of Supervisory Board: Markus Ochsner

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und
vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser Mail ist nicht gestattet. 

Bitte beachten Sie auch unsere Datenschutzerklärung für Geschäftspartner,
die Sie über unsere  <https://new.abb.com/privacy-policy/de/datenschutz>
Webseite oder direkt unter diesem
<https://new.abb.com/docs/librariesprovider30/default-document-library/daten
schutzerklärung-geschäftspartner-abb-ag_de832794ecc1f463c09537ff0000433538.p
df> Link finden.

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this e-mail in error)
please notify the sender immediately and destroy this e-mail. Any
unauthorized copying, disclosure or distribution of the material in this
e-mail is strictly forbidden.

Please also take note of our data protection notice for business partners,
which you can find on our
<https://new.abb.com/privacy-policy/de/datenschutz> web page or directly
under the following
<https://new.abb.com/docs/librariesprovider30/default-document-library/data-
protection-notice-business-partners-abb-ag_de762794ecc1f463c09537ff000043353
8.pdf> link.

 

From: Martin Prpič ***@***.***> 
Sent: Mittwoch, 15. Dezember 2021 14:09
To: RedHatProductSecurity/cvelib ***@***.***>
Cc: Ragnar Schierholz ***@***.***>; Mention
***@***.***>
Subject: Re: [RedHatProductSecurity/cvelib] Protection of API key (Issue
#13)

 

	
This email originated from outside of your organization. Please do not click
on links or open attachments unless you recognize the sender and know the
content is safe. 

 

Hey @raschi-de
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fraschi-de&data=04%7C01%7Cragnar.schierholz%40de.abb.com%7Ccc0271d977b647
5f0b1e08d9bfcc0e8d%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637751705412
781834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6I
k1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hexmat3Ia4EPFdiwWYTRhzrNYNIFhF1aBIVqb9FJr
mc%3D&reserved=0> , not a stupid question at all :-) I pushed the fix to
this repo but have not published an updated package of cvelib to PyPI yet so
the version available there (0.5.0 at the moment) does not contain this code
change. I'll push out a new update some time today and then you can just run
python3 -m pip install --upgrade. Look out for a new release to be available
in either of these places:

*	https://pypi.org/project/cvelib/#history
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpypi.org%
2Fproject%2Fcvelib%2F%23history&data=04%7C01%7Cragnar.schierholz%40de.abb.co
m%7Ccc0271d977b6475f0b1e08d9bfcc0e8d%7C372ee9e09ce04033a64ac07073a91ecd%7C0%
7C0%7C637751705412781834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjo
iV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FejzTXiUmlTRLYw9BMYF5
%2BNMBfH5b6BU4KYl7Fl4k8M%3D&reserved=0> 
*	https://github.com/RedHatProductSecurity/cvelib/releases
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FRedHatProductSecurity%2Fcvelib%2Freleases&data=04%7C01%7Cragnar.schierho
lz%40de.abb.com%7Ccc0271d977b6475f0b1e08d9bfcc0e8d%7C372ee9e09ce04033a64ac07
073a91ecd%7C0%7C0%7C637751705412781834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wL
jAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fWH7SbX3a
HhamrLkx2lpgUFWb6p1cyLvhGhRlzDC37g%3D&reserved=0> 

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2FRedHatProductSecurity%2Fcvelib%2Fissues%2F13%23issuecomment-994775431&da
ta=04%7C01%7Cragnar.schierholz%40de.abb.com%7Ccc0271d977b6475f0b1e08d9bfcc0e
8d%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637751705412781834%7CUnknown
%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6M
n0%3D%7C3000&sdata=IQipgRmlEMTpmqfxn92NaZgq8Ak6A3OffjDejhfKQG8%3D&reserved=0
> , or unsubscribe
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.co
m%2Fnotifications%2Funsubscribe-auth%2FAQYN5KQOXPYUYTXFWPMWKXDURCHOTANCNFSM5
JZPVHGA&data=04%7C01%7Cragnar.schierholz%40de.abb.com%7Ccc0271d977b6475f0b1e
08d9bfcc0e8d%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637751705412781834
%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWw
iLCJXVCI6Mn0%3D%7C3000&sdata=K1K9uY02Qs4l5KL50yrhuFwbA2PknSz0QJ5706J%2F5KA%3
D&reserved=0> .
Triage notifications on the go with GitHub Mobile for iOS
<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.appl
e.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%
26pt%3D524675&data=04%7C01%7Cragnar.schierholz%40de.abb.com%7Ccc0271d977b647
5f0b1e08d9bfcc0e8d%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637751705412
781834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6I
k1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AN7mms6L69xPqjiz12MczpsSbd7fmnDL28WqVC4Zi
eI%3D&reserved=0>  or Android.
