### ISSUE TITLE
Support both create and update CVE records in the newly created publish method.

### ISSUE THREAD

**Issue by sei-vsarvepalli** [RedHatProductSecurity/cvelib#25]
The method publish should also support  Update which is basically an `HTTP PUT` instead of a `POST`

https://github.com/RedHatProductSecurity/cvelib/blob/86588fe482558e3a227df8e000ce0ce920c5605f/cvelib/cve_api.py#L90-L95

So something like below with appropriate updates to cli.py, test_cli.py for the use case of updated a CVE record. 
```
 def publish(self, cve_id, cve_json,update=False): 
     """Publish or Update a CVE from a JSON object representing the CNA container data.""" 
     cve_json = {"cnaContainer": cve_json}
     if update:
         response = self.put(f"cve/{cve_id}/cna", json=cve_json)
     else:
         response = self.post(f"cve/{cve_id}/cna", json=cve_json) 
     response.raise_for_status() 
     return response.json()
```

**Comment by sei-vsarvepalli** [comment]
Sounds good.  I was updating the JavaScript client and found the code where this updateCna is called.  As far as I can tell the method seems to replace the whole cna.container object.  Another thing may be more clear once swagger can be organized to create API documentation.

https://github.com/CVEProject/cve-services/blob/f0192a280e1ada14c5483555ab3e0fc9426a2ab2/src/controller/cve.controller/index.js#L68-L76

https://github.com/CVEProject/cve-services/blob/f5f775698ed27853c9494507b0dfbdac824d67db/src/controller/cve.controller/cve.controller.js#L419

**Comment by mprpic** [comment]
This was resolved by https://github.com/RedHatProductSecurity/cvelib/commit/8f88d36532954db873e98bca08adedebe32cb2ad, which will be merged to master after the 2.x release of CVE Services.
