### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by shadrak98** [RedHatProductSecurity/cvelib#26]
This error was thrown on python3.7. 

<img width="569" alt="Screenshot 2022-05-02 at 2 35 39 PM" src="https://user-images.githubusercontent.com/30501401/166210895-9cf8f4a9-5a7c-43f1-8dc3-7a07a1034142.png">

Resolved it with the help of this: https://stackoverflow.com/a/64404967

**Comment by mprpic** [comment]
Thanks for reporting this, also uncovered a problem in the test runner wherein it was executing only tests against Python 3.10 :facepalm:.
