### ISSUE TITLE
Feature request: make cve records with a single quote in their body easy to submit

### ISSUE THREAD

**Issue by MrSeccubus** [RedHatProductSecurity/cvelib#47]
If you want to submit a CVE record that has signe quotes in them, it is hard to make the shell syntax work.

Solutions would be:
* Allowing the json to be read form a file
* Allowing the json to be read from stdin

**Comment by MrSeccubus** [comment]
You will get this is you make a record with vulnogram and select the following problem type:
```
"problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-1321",
                            "description": "CWE-1321: Improperly Controlled Modification of Object Prototype Attributes (\"Prototype Pollution\")",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
```

**Comment by mprpic** [comment]
The `publish` command already has submission from a file as an option:
```
-f, --cve-json-file FILENAME  File containing JSON body of CVE record to publish.
```
It's only available on master but I can do a new release by the end of the week to also include some of the changes from the other  issues you filed.

**Comment by MrSeccubus** [comment]
Thanks @mprpic, Much appreciated.
