### ISSUE TITLE
Weaken dependency on required version jsonschema?

### ISSUE THREAD

**Issue by carnil** [RedHatProductSecurity/cvelib#53]
Hi

7dfa855d23eef0af71218ad116a04e1076b5f892 added a quite strong dependency to `jsonschema>=4.17.0` which is the very newest jsonschema upstream release. 

Packaging cvelib downstream in Debian I wonder if we can relax the version to the minimum required one? @mprpic  can this be done or is 4.17.0 the actual required one? The testsuite passes for me with 4.7.2 available.

Thanks for your work making cvelib possible!

**Comment by mprpic** [comment]
Yea, that makes sense. I set it back to 4.7.2 in #54, let me know if that works!

**Comment by carnil** [comment]
@mprpic thanks! (4.7.2 seems to be sufficient, the test suite passes and some manual interaction went fine, but was not able to test all features)
