### ISSUE TITLE
possible API change to `cve list`

### ISSUE THREAD

**Issue by eslerm** [RedHatProductSecurity/cvelib#76]
During `cve list`, it is no longer guaranteed that `cve['requested_by']['user']` is true. If a user is unknown, it is not being set. This appears to be due to change in the CVE Services API which occurred since Jan 11 2024.

To fix this I'm using the following in `cve_list()`: 
```
    for cve in cves:
        user = "pre_idr_user"
        if 'user' in cve['requested_by']:
            user = cve['requested_by']['user']
        lines.append(
            ( 
                cve["cve_id"],
                cve["state"],
                cve["owning_cna"],
                f"{user} ({cve['requested_by']['cna']})",
                human_ts(cve["reserved"]),
            )
        )
```

What is odd, is that old CVEs which lack a user can still be called with `cve show $CVE_ID`, even though `print_cve_id()` calls `cve['requested_by']['user']`.

**Comment by dsommers** [comment]
I can confirm the same issue.  `pip3.11 install cvelib` on RHEL-8.

**Comment by mprpic** [comment]
Related issue in cve-services: https://github.com/CVEProject/cve-services/issues/1176
