### ISSUE TITLE
No API key in new user creation & reset token for a user resets my token

### ISSUE THREAD

**Issue by AlastairPooley** [RedHatProductSecurity/cvelib#8]
I’m using the Redhat client to create a new user but didn’t get an API key in the response. I tried using reset-token for the user but it reset mine instead of the user key.

**Comment by mprpic** [comment]
![cve_user](https://user-images.githubusercontent.com/493157/136075948-d410d75d-73b9-4012-87e8-f9d1c0699ee0.png)
