### ISSUE TITLE
mark-active and mark-inactive seem to affect the active user and not the selected one

### ISSUE THREAD

**Issue by CERT-VDE** [RedHatProductSecurity/cvelib#86]
Hey there,

I tried to mark a user inactive (user -u username@domain.tld update --mark-inactive), got the response that the update went through but can't use the API afterwards. So one of my colleagues checked within their account and could confirm, that my account has been set inactive instead of the one that was planned to be set inactive.
However my colleagues are not able to reactivate my account, all tags with --mark-(in)active seem to affect the active user only, not the one selected with -u username.
Affected versions seem to be 1.2.x up to 1.4.0

Thank you,
CERT@VDE
/jochen

**Comment by mprpic** [comment]
Also worth noting that perhaps using interactive mode would have prevented this:

```
> cve -i user update -u test@redhat.com --mark-inactive
You are about to update the test@redhat.com user with the following changes:

- active: false

Do you want to continue? [y/N]: n
Exiting...

> cve -i user -u test@redhat.com update --mark-inactive
You are about to update the mprpic@redhat.com user with the following changes:

- active: false

Do you want to continue? [y/N]: n
```

If you have ideas of how to improve the user experience, do share :wink:

**Comment by CERT-VDE** [comment]
Thank you for clarification @mprpic !

My idea would be to force the `-u` after `update` to when using `--mark-inactive` or `--mark-active`. That should prevent users that are not able to understand the help (like me 😉) to accidentally lockout themselves.
Another option would be to use something like --target-user instead of -u after update...
However, with your help a colleague was able to mark my account as active again, thank you.

/Jochen

**Comment by mprpic** [comment]
See linked MR where I made the `-u` option required so that it's more explicit about which user is being updated.
