### ISSUE TITLE
Don't fail if -u, -o or -a are not supplied for `cve validate` command

### ISSUE THREAD

**Issue by carnil** [RedHatProductSecurity/cvelib#98]
Hi

This is actually similar to https://github.com/RedHatProductSecurity/cvelib/issues/92 but for the new added `cve validate` subcommand. AFAIU, the validation is against all local data, so I would expect 

```
cve validate -s full -f ./tests/data/CVEv5_advanced-example.json
```

to just work without `-u`, `-o` and `-a`.

Is this correct?

**Comment by mprpic** [comment]
Ah, thanks for the report. Fixed in linked PR!
